server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/home_energy_tracker
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
        ddl-auto: none

